name: wallpaper_handler
description: Flutter package for easy wallpaper customization on Android devices – change Home Screen, Lock Screen, or both with simplicity.
version: 0.0.3
homepage: https://www.sahkari.tech
repository: https://github.com/sahkari/wallpaper_handler
issue_tracker: https://github.com/sahkari/wallpaper_handler/issues

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.wallpaper_handler
        pluginClass: WallpaperHandlerPlugin

topics:
  - wallpaper-handler
  - wallpaper
  - wallpaper-change
  - wallpaper-set
  - home-screen
  - lock-screen
  - flutter-wallpaper
  - wallpaper-app
  - android-wallpaper